### ISSUE TITLE
Documentation not found

### ISSUE THREAD

**Issue by Lawrence-Pet** [CommonRoad/commonroad-io#2]
The link for the documentation keeps returning a 404 error. 

https://commonroad-io.readthedocs.io/en/latest/

**Comment by smaierhofer** [comment]
This link is outdated. The correct one is https://cps.pages.gitlab.lrz.de/commonroad/commonroad-io/
Where have you found this link so that we can update it?

**Comment by Lawrence-Pet** [comment]
Hi, thanks!
It is both in the tutorial notebooks and in the readme.md in root of this repository. 
I also believed I encountered it on the webpage for commonroads, but I was unable to find that specific one in this moment.

**Comment by smaierhofer** [comment]
The links in the readme and tutorial notebooks within this repository are now updated on the develop branch. 
The links on the website will be updated later.
